name: webserv test
on: [push]
env:
  BUILD_PARALLEL: 16
  SLEEP_BEFORE_TEST: 5
  TEST_DIR: tests_build
  TEST_BIN: webserv-test

jobs:
  make-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - run: mkdir -p ./${{ env.TEST_DIR }}
      - run: cd ./${{ env.TEST_DIR }} && cmake ..
      - run: make -C ./${{ env.TEST_DIR }} -j${{ env.BUILD_PARALLEL }}
      - run: ./${{ env.TEST_DIR }}/${{ env.TEST_BIN }} --gtest_color=yes

  test-python-http:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: make -j${{ env.BUILD_PARALLEL }}
      - run: sudo ./webserv &
        id: exec-webserv
      - run: sleep ${{ env.SLEEP_BEFORE_TEST }}
      - run: python3 test-ci/http-test.py
      - if: always() &&  steps.exec-webserv.outcome == 'success'
        name: Find latest log file
        id: latest-log
        run: echo "file=$(ls -t logs | head -n 1)" >> $GITHUB_OUTPUT
        continue-on-error: true
      - if: always() &&  steps.exec-webserv.outcome == 'success'
        run: sudo kill $(pgrep webserv)
        continue-on-error: true
      - if: always() &&  steps.exec-webserv.outcome == 'success'
        run: cat logs/${{ steps.latest-log.outputs.file }}
      - if: always() &&  steps.exec-webserv.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: webserv-${{ matrix.os }}-log
          path: logs/${{ steps.latest-log.outputs.file }}

  debug-test-python-http:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: make debug -j${{ env.BUILD_PARALLEL }}
      - run: sudo ./debug &
        id: exec-webserv
      - run: sleep ${{ env.SLEEP_BEFORE_TEST }}
      - run: python3 test-ci/http-test.py
      - if: always() && steps.exec-webserv.outcome == 'success'
        name: Find latest log file
        id: latest-log
        run: echo "file=$(ls -t logs | head -n 1)" >> $GITHUB_OUTPUT
        continue-on-error: true
      - if: always() && steps.exec-webserv.outcome == 'success'
        run: sudo kill $(cat debug.pid)
        continue-on-error: true
      - if: always() && steps.exec-webserv.outcome == 'success'
        run: cat logs/${{ steps.latest-log.outputs.file }}
      - if: always() && steps.exec-webserv.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ matrix.os }}-log
          path: logs/${{ steps.latest-log.outputs.file }}
